### ISSUE TITLE
Playtime discrepency with wynncraft website/wynndata

### ISSUE THREAD

**Issue by MikhaD** [motoki317/moto-bot#172]
For the `>stats` command the players playtime is listed in the format days hours minutes, treating the playtime property's value as minutes, like it is described in the api documentation. However, the Wynncraft website lists a playtime that is roughly 5 times greater, as does wynndata. Is playtime meant to represent 5 minute increments instead of single minute increments as stated?

**Comment by motoki317** [comment]
> Is playtime meant to represent 5 minute increments instead of single minute increments as stated?

I'm not the one to answer this question, refer to the following issue (and ask Wynn devs) instead.
https://github.com/Wynncraft/WynncraftAPI/issues/56

But since this discrepancy has been in the API for years and I doubt they'll fix this anytime soon, I guess it's reasonable to have playtime multiplied by 5 (or 4.7) in the meantime.
